version: "3.9"

services:
  # No PostgreSQL needed - using Firestore
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-gcp
    container_name: piratephilosopher_backend
    environment:
      # GCP Configuration
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/gcp-credentials.json
      GCP_PROJECT_ID: piratephilosopher
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000}
    volumes:
      # Mount GCP credentials into container
      - ${HOME}/.config/gcloud/piratephilosopher-credentials.json:/app/credentials/gcp-credentials.json:ro
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: piratephilosopher_frontend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    ports:
      - "3000:3000"