#!/usr/bin/env python3
"""
Módulo con biografías detalladas para usar en seed.py
"""

def get_author_biography(name: str) -> str:
    """Devuelve una biografía detallada para el autor o una biografía genérica"""
    
    DETAILED_BIOGRAPHIES = {
        # Filósofos Griegos Clásicos
        "Sócrates": "Filósofo griego considerado el fundador de la filosofía occidental. Desarrolló el método socrático de investigación basado en preguntas. No escribió ningún texto, conocemos su pensamiento através de Platón. Fue condenado a muerte por corromper a la juventud y no creer en los dioses de la ciudad.",
        
        "Platón": "Discípulo de Sócrates y maestro de Aristóteles. Fundó la Academia en Atenas. Su filosofía se centra en la teoría de las Ideas o Formas, mundos perfectos e inmutables que trascienden la realidad sensible. Escribió numerosos diálogos donde Sócrates es el personaje principal.",
        
        "Aristóteles": "Filósofo griego discípulo de Platón. Fundó el Liceo y desarrolló un sistema filosófico completo que abarca lógica, ética, política, metafísica y ciencias naturales. Fue tutor de Alejandro Magno. Su influencia se extendió por siglos en el pensamiento occidental.",
        
        "Epicuro": "Filósofo griego fundador del epicureísmo. Propuso que el objetivo de la vida humana es alcanzar la felicidad y evitar el dolor. Distinguió entre placeres necesarios e innecesarios. Fundó el Jardín, una comunidad filosófica que incluía mujeres y esclavos.",
        
        "Zenón de Citio": "Fundador del estoicismo en Atenas. Enseñaba en el Pórtico Pintado (Stoa Poikile). Los estoicos creían en vivir de acuerdo con la naturaleza y aceptar lo que no podemos cambiar, desarrollando virtudes como la sabiduría, justicia, fortaleza y templanza.",
        
        "Pitágoras": "Filósofo y matemático griego famoso por el teorema que lleva su nombre. Fundó una escuela filosófico-religiosa que creía en la transmigración de las almas y en que los números son la esencia de todas las cosas. Influyó profundamente en Platón.",
        
        "Heráclito": "Filósofo presocrático conocido como 'el Oscuro' por su estilo enigmático. Famoso por su doctrina del flujo constante ('no puedes bañarte dos veces en el mismo río') y la unidad de los opuestos. Consideraba el fuego como el elemento primordial.",
        
        "Parménides": "Filósofo presocrático que defendió la inmutabilidad del ser. En su poema 'Sobre la naturaleza' distingue entre el camino de la verdad y el de la opinión. Influyó profundamente en Platón y en toda la metafísica occidental posterior.",
        
        # Estoicos Romanos
        "Séneca": "Filósofo estoico romano, dramaturgo y político. Fue preceptor y consejero del emperador Nerón. Sus 'Cartas a Lucilio' y tratados morales son fundamentales del estoicismo. Defendió la ética práctica y la autosuficiencia moral.",
        
        "Marco Aurelio": "Emperador romano y filósofo estoico. Sus 'Meditaciones', escritas para sí mismo, son una de las obras más importantes del estoicismo tardío. Combinó poder político con sabiduría filosófica, siendo considerado el último de los 'cinco buenos emperadores'.",
        
        "Epicteto": "Filósofo estoico nacido esclavo que se convirtió en uno de los maestros más influyentes del estoicismo tardío. Sus 'Discursos' y el 'Manual' (Enquiridión) enseñan la importancia de distinguir entre lo que depende de nosotros y lo que no.",
        
        # Filósofos Medievales
        "Tomás de Aquino": "Santo Tomás de Aquino, teólogo y filósofo italiano del siglo XIII. Sintetizó la filosofía aristotélica con la doctrina cristiana en su 'Suma Teológica'. Desarrolló las cinco vías para demostrar la existencia de Dios. Es el principal representante de la escolástica y Doctor de la Iglesia.",
        
        "San Agustín": "Aurelio Agustín de Hipona, teólogo y filósofo cristiano del siglo IV-V. Sus 'Confesiones' son pioneras del género autobiográfico. En 'La Ciudad de Dios' desarrolla una filosofía cristiana de la historia. Sintetizó cristianismo y platonismo, influyendo en toda la filosofía medieval.",
        
        # Filosofía Oriental
        "Confucio": "Kong Qiu, pensador chino del siglo VI-V a.C. Sus enseñanzas, recopiladas en las 'Analectas', enfatizan la moralidad personal, la rectitud en las relaciones sociales y la justicia. El confucianismo se convirtió en la doctrina oficial del Estado chino durante siglos.",
        
        "Lao Tzu": "Legendario fundador del taoísmo en el siglo VI a.C. El 'Tao Te Ching' que se le atribuye es fundamental para entender el taoísmo. Enseña sobre el Tao (el Camino), el wu wei (no-acción) y la armonía con la naturaleza.",
        
        "Buda": "Siddhartha Gautama, fundador del budismo en el siglo VI-V a.C. Tras alcanzar la iluminación bajo el árbol Bodhi, enseñó las Cuatro Nobles Verdades y el Óctuple Sendero como camino para superar el sufrimiento y alcanzar el Nirvana.",
        
        # Filósofos Modernos
        "René Descartes": "Filósofo y matemático francés del siglo XVII, considerado padre de la filosofía moderna. Su método de duda sistemática lo llevó al 'cogito ergo sum' (pienso, luego existo). Estableció el dualismo mente-cuerpo y revolucionó tanto filosofía como matemáticas.",
        
        "Baruch Spinoza": "Filósofo holandés del siglo XVII. Su 'Ética' presenta un sistema filosófico geométrico donde Dios y la Naturaleza son idénticos. Defendió el determinismo absoluto y una ética basada en el conocimiento racional. Fue excomulgado de la comunidad judía por sus ideas.",
        
        "John Locke": "Filósofo inglés del siglo XVII, padre del empirismo moderno y del liberalismo político. Su 'Ensayo sobre el entendimiento humano' niega las ideas innatas. Sus 'Dos tratados sobre el gobierno civil' influyeron en las revoluciones americana y francesa.",
        
        "David Hume": "Filósofo escocés del siglo XVIII, figura clave del empirismo y la Ilustración escocesa. Su escepticismo sobre la causalidad y la inducción despertó a Kant de su 'sueño dogmático'. Escribió importantes trabajos sobre religión, moral e historia.",
        
        "Immanuel Kant": "Filósofo alemán del siglo XVIII, figura central de la filosofía moderna. Su 'Crítica de la razón pura' sintetiza racionalismo y empirismo. Desarrolló la ética del deber categórico y la idea de la 'paz perpetua'. Revolucionó metafísica, epistemología y ética.",
        
        "Georg Hegel": "Filósofo alemán del siglo XIX. Su sistema dialéctico comprende toda la realidad como desarrollo del Espíritu Absoluto a través de tesis, antítesis y síntesis. Su filosofía de la historia y del Estado influyó profundamente en el pensamiento posterior.",
        
        "Friedrich Nietzsche": "Filósofo alemán del siglo XIX. Proclamó la 'muerte de Dios' y desarrolló conceptos como el 'superhombre', la 'voluntad de poder' y el 'eterno retorno'. Su crítica de la moral occidental y su estilo aforístico influyeron enormemente en el pensamiento contemporáneo.",
        
        "Karl Marx": "Filósofo, economista y revolucionario alemán del siglo XIX. Desarrolló el materialismo histórico y la crítica de la economía política capitalista. Su análisis de la lucha de clases y la alienación influyó profundamente en la política y filosofía del siglo XX.",
        
        # Filósofos Contemporáneos  
        "Ludwig Wittgenstein": "Filósofo austro-británico del siglo XX. Su 'Tractus Logico-Philosophicus' influyó en el positivismo lógico. Posteriormente, sus 'Investigaciones filosóficas' revolucionaron la filosofía del lenguaje con la teoría de los 'juegos del lenguaje'.",
        
        "Jean-Paul Sartre": "Filósofo francés del siglo XX, figura principal del existencialismo. Su máxima 'la existencia precede a la esencia' enfatiza la libertad y responsabilidad humanas. También fue novelista, dramaturgo y activista político comprometido.",
        
        "Simone de Beauvoir": "Filósofa francesa del siglo XX, pionera del feminismo moderno. Su obra 'El segundo sexo' analiza la construcción social de la feminidad y la opresión de la mujer. También desarrolló importantes contribuciones al existencialismo.",
        
        "Hannah Arendt": "Filósofa política alemana-estadounidense del siglo XX. Analizó el totalitarismo, la naturaleza del poder y la condición humana. Su concepto de 'banalidad del mal' y su distinción entre labor, trabajo y acción influyeron en la teoría política contemporánea.",
        
        # Filósofos Modernos y Contemporáneos añadidos
        "José Ortega y Gasset": "Filósofo español del siglo XX, figura central de la filosofía hispana. Desarrolló el perspectivismo y el concepto de 'razón vital'. Su obra 'La rebelión de las masas' analiza la sociedad de masas moderna. Fundó la Revista de Occidente, crucial para la modernización intelectual de España.",
        
        "María Zambrano": "Filósofa española discípula de Ortega y Gasset. Desarrolló una filosofía poética que integra razón y corazón. Su 'razón poética' busca superar la crisis de la razón moderna. Exiliada durante el franquismo, es una de las pensadoras más originales del siglo XX.",
        
        "Miguel de Unamuno": "Filósofo y escritor español, figura clave de la Generación del 98. Su obra 'Del sentimiento trágico de la vida' explora la tensión entre razón y fe. Desarrolló el concepto de 'intrahistoria' y exploró temas existenciales como la inmortalidad y la agonía del cristianismo.",
        
        "Henri Bergson": "Filósofo francés Premio Nobel de Literatura 1927. Desarrolló una filosofía vitalista que enfatiza la intuición sobre el intelecto. Sus obras sobre el tiempo, la memoria y la evolución creadora influyeron profundamente en la filosofía y las artes del siglo XX.",
        
        "Bertrand Russell": "Filósofo, lógico y matemático británico, Premio Nobel de Literatura 1950. Junto con Whitehead desarrolló los 'Principia Mathematica'. Sus contribuciones a la lógica, filosofía del lenguaje y epistemología fueron fundamentales. También fue activista pacifista y social.",
        
        "William James": "Filósofo y psicólogo estadounidense, fundador del pragmatismo junto con Pierce y Dewey. Desarrolló el 'empirismo radical' y estudios pioneros sobre experiencia religiosa y conciencia. Su teoría de la verdad como 'lo que funciona' influyó enormemente en la filosofía americana.",
        
        "John Dewey": "Filósofo estadounidense, principal exponente del pragmatismo. Revolucionó la educación con su filosofía 'aprender haciendo'. Sus trabajos sobre democracia, educación y experiencia lo convierten en una figura fundamental del pensamiento progresista americano.",
        
        "Max Weber": "Sociólogo, economista y filósofo alemán, figura fundacional de la sociología moderna. Su 'Ética protestante y el espíritu del capitalismo' es fundamental para entender la modernidad. Desarrolló conceptos como 'tipos ideales', 'desencantamiento del mundo' y análisis de la burocracia.",
        
        "Alfred North Whitehead": "Matemático y filósofo británico, coautor con Russell de los 'Principia Mathematica'. Desarrolló la 'filosofía del proceso', una metafísica que ve la realidad como constituida por procesos antes que sustancias. Su pensamiento influyó en teología, cosmología y filosofía de la ciencia.",
        
        "Hans-Georg Gadamer": "Filósofo alemán, principal exponente de la hermenéutica filosófica. Su obra 'Verdad y método' revolucionó la comprensión de la interpretación. Desarrolló conceptos como 'fusión de horizontes' y 'círculo hermenéutico', fundamentales para las ciencias humanas y la filosofía continental.",
        
        "Paul Ricoeur": "Filósofo francés que integró hermenéutica, fenomenología y estructuralismo. Sus trabajos sobre narratividad, memoria e identidad personal son fundamentales. Desarrolló una 'hermenéutica del sí mismo' y contribuyó significativamente a la filosofía del lenguaje y la ética.",
        
        "Walter Benjamin": "Filósofo y crítico cultural alemán asociado con la Escuela de Frankfurt. Sus ensayos sobre arte, literatura y cultura moderna, como 'La obra de arte en la época de su reproductibilidad técnica', fueron revolucionarios. Su pensamiento combina marxismo, misticismo judío y crítica estética.",
        
        "Antonio Gramsci": "Filósofo y teórico político italiano, fundador del Partido Comunista Italiano. Desarrolló conceptos como 'hegemonía cultural' y 'intelectual orgánico'. Sus 'Cuadernos de la cárcel', escritos durante su encarcelamiento fascista, renovaron profundamente la teoría marxista.",
        
        "Michel Foucault": "Filósofo francés del siglo XX, figura clave del postestructuralismo. Sus análisis sobre poder, saber y sexualidad revolucionaron las ciencias humanas. Obras como 'Historia de la locura', 'Vigilar y castigar' y 'Historia de la sexualidad' influyeron profundamente en filosofía, sociología e historia.",
        
        # EXPANSIÓN MASIVA DE BIOGRAFÍAS - Filósofos Griegos Presocráticos
        "Tales de Mileto": "Tales de Mileto (c. 624-546 a.C.), considerado el primer filósofo occidental y fundador de la filosofía natural griega. Miembro de los Siete Sabios de Grecia, fue matemático, astrónomo y político. Propuso que el agua es el principio fundamental (arjé) de todas las cosas, rompiendo con las explicaciones míticas tradicionales. Predijo el eclipse solar del 585 a.C., lo que demuestra sus conocimientos astronómicos avanzados. Desarrolló teoremas geométricos fundamentales y fue mentor de Anaximandro. Su enfoque racional para explicar los fenómenos naturales sin recurrir a dioses marca el nacimiento del pensamiento científico occidental.",
        
        "Anaximandro": "Anaximandro de Mileto (c. 610-546 a.C.), discípulo de Tales y segundo filósofo de la escuela de Mileto. Propuso el 'ápeiron' (lo indefinido, infinito e indeterminado) como principio universal, superando la teoría del agua de su maestro. Creó el primer mapa del mundo conocido y desarrolló un modelo cosmológico revolucionario donde la Tierra flota libremente en el espacio. Sus teorías evolutivas primitivas sugieren que los humanos descienden de peces. Inventó el reloj de sol en Grecia y realizó importantes observaciones astronómicas. Su concepto de justicia cósmica influyó en toda la filosofía posterior, estableciendo que los opuestos se equilibran mutuamente en el cosmos.",
        
        "Anaxímenes": "Anaxímenes de Mileto (c. 585-528 a.C.), último filósofo de la escuela de Mileto y discípulo de Anaximandro. Propuso el aire (aer) como elemento primordial y principio de todas las cosas, desarrollando una teoría sofisticada sobre condensación y rarefacción. Según su cosmología, el aire condensado forma agua y tierra, mientras que rarefaccionado se convierte en fuego. Explicó fenómenos meteorológicos como terremotos, rayos y arcoíris mediante procesos naturales del aire. Su modelo cosmológico influyó en filósofos posteriores como Heráclito y los atomistas. Representó un retorno a explicaciones materiales simples después de las abstracciones de Anaximandro, estableciendo metodologías que perdurarían en la filosofía natural.",
        
        "Jenófanes": "Jenófanes de Colofón (c. 570-475 a.C.), filósofo y poeta elegíaco que criticó radicalmente el antropomorfismo religioso de su época. Atacó las representaciones humanas de los dioses en Homero y Hesíodo, argumentando que si los animales pudieran crear dioses, los harían a su imagen. Propuso un monoteísmo filosófico con un dios único, inmóvil y que gobierna mediante su mente. Desarrolló ideas epistemológicas avanzadas sobre la diferencia entre conocimiento y opinión. Sus observaciones geológicas de fósiles marinos en montañas lo llevaron a teorías sobre cambios cíclicos de la Tierra. Influyó significativamente en Parménides y la escuela eleática, estableciendo bases para la crítica racional de la religión tradicional.",
        
        "Empédocles": "Empédocles de Agrigento (c. 494-434 a.C.), filósofo, poeta, médico, político y taumaturgo que desarrolló la teoría de los cuatro elementos clásicos: tierra, agua, aire y fuego. Estas 'raíces' se combinan y separan mediante dos fuerzas cósmicas: Amor (Philotes) y Discordia (Neikos), creando ciclos eternos de unión y separación. Su teoría de la percepción mediante 'poros' (poros) influyó en toda la óptica antigua. Desarrolló ideas evolutivas sobre la supervivencia del más apto y teorías sobre la reencarnación del alma. Como político, defendió la democracia en Agrigento. Sus poemas 'Sobre la naturaleza' y 'Purificaciones' combinan filosofía natural con elementos místico-religiosos, influyendo en Platón y la tradición médica hipocrática.",
        
        "Anaxágoras": "Anaxágoras de Clazómenas (c. 500-428 a.C.), primer filósofo en establecerse en Atenas, donde influyó en Pericles y Eurípides. Desarrolló la teoría de las 'homeomerías' o 'semillas' (spermata) - partículas infinitesimales que contienen porciones de todas las cualidades. Propuso el 'Nous' (Mente) como principio ordenador del cosmos, la primera concepción clara de una inteligencia cósmica. Explicó correctamente las fases lunares y eclipses, y teorías sobre la Vía Láctea como concentración de estrellas distantes. Fue procesado por impiedade por afirmar que el sol era una piedra ardiente mayor que el Peloponeso. Su separación entre mente y materia preparó el dualismo platónico y su método de explicación mecánica influyó en el atomismo de Demócrito.",
        
        # Filósofos Griegos Clásicos - Expansión
        "Protágoras": "Protágoras de Abdera (c. 490-420 a.C.), el más famoso de los sofistas y primer pensador en cobrar por enseñar filosofía. Su célebre máxima 'el hombre es la medida de todas las cosas' establece un relativismo epistemológico revolucionario. Desarrolló la técnica de los 'discursos dobles' (antilogiae), demostrando que sobre cualquier tema pueden sostenerse dos argumentos opuestos igualmente válidos. Su agnosticismo religioso ('sobre los dioses no puedo saber si existen o no') causó controversia en Atenas. Creó el primer sistema formal de gramática griega, distinguiendo géneros y tiempos verbales. Como educador, prometía hacer 'fuerte el argumento débil', enseñando retórica y dialéctica. Sus ideas relativistas influyeron profundamente en Platón, quien desarrolló su filosofía en parte como respuesta a las tesis protagóreas.",
        
        "Gorgias": "Gorgias de Leontinos (c. 483-375 a.C.), sofista y retórico que revolucionó la oratoria griega con su estilo poético y figuras elaboradas. Su obra 'Sobre el no-ser' presenta tres tesis nihilistas: nada existe, si algo existiera no sería cognoscible, y si fuera cognoscible no sería comunicable. Estas paradojas desafiaron los fundamentos de la filosofía eleática y la posibilidad misma del conocimiento. Como embajador de Leontinos en Atenas (427 a.C.), impresionó con su elocuencia y estableció la retórica como arte independiente. Desarrolló figuras retóricas específicas (gorgianismos) como antítesis, isocolon y paronomasia. Su 'Encomio de Helena' y 'Defensa de Palamedes' demuestran el poder del logos para persuadir independientemente de la verdad. Influyó en Isócrates y toda la tradición retórica posterior, estableciendo que el lenguaje crea realidad tanto como la describe.",
        
        # Filósofos Estoicos - Expansión masiva
        "Antístenes": "Antístenes de Atenas (c. 445-365 a.C.), discípulo de Sócrates y fundador de la escuela cínica, precursora del estoicismo. Desarrolló una ética radical basada en la autosuficiencia (autarkeia) y el desprecio por las convenciones sociales. Su famoso lema 'la virtud basta para la felicidad' influyó decisivamente en el estoicismo posterior. Enseñó que el sabio debe ser independiente de bienes externos, placeres y dolor. Sus teorías sobre el lenguaje anticiparon debates lógicos posteriores, argumentando que solo pueden hacerse juicios de identidad ('el hombre es hombre') pero no predicaciones ('el hombre es bueno'). Mentor de Diógenes de Sínope, transmitió el ideal socrático de vida filosófica práctica. Sus obras (perdidas) abarcaban ética, política, teología y teoría del conocimiento, estableciendo bases conceptuales para movimientos filosóficos posteriores que priorizaban la vida virtuosa sobre el conocimiento teórico.",
        
        "Cleantes": "Cleantes de Asos (c. 331-232 a.C.), segundo escolarca de la escuela estoica tras Zenón de Citio, quien desarrolló y sistematizó la doctrina estoica temprana. Conocido como 'el segundo fundador del estoicismo', trabajó como boxeador nocturno para financiar sus estudios filosóficos durante el día. Su 'Himno a Zeus' es la expresión poética más hermosa de la teología estoica, identificando a Zeus con el Logos divino que gobierna el cosmos. Desarrolló la teoría estoica del pneuma (aliento vital) como principio material que unifica cuerpo y alma. Su física materialista sostuvo que todo lo que existe es corpóreo, incluyendo virtudes, emociones y conceptos. Defendió la doctrina de la conflagración universal (ekpyrosis), el ciclo cósmico de destrucción y regeneración. Sus contribuciones a la lógica estoica incluyeron refinamientos en la teoría de las proposiciones condicionales, influyendo en toda la lógica occidental posterior.",
        
        # Filósofos Helenísticos y Romanos - Expansión
        "Alejandro de Afrodisias": "Alejandro de Afrodisias (c. 150-215 d.C.), el más importante comentarista de Aristóteles en la antigüedad tardía, conocido como 'el Comentarista' por excelencia. Director de la escuela aristotélica en Atenas, sus exhaustivos comentarios preservaron y transmitieron el aristotelismo auténtico durante siglos. Desarrolló una interpretación materialista de la psicología aristotélica, argumentando que el alma intelectiva es mortal y específica a cada individuo, oponiéndose a interpretaciones platónicas. Su tratado 'Sobre el destino' defiende la compatibilidad entre determinismo causal y responsabilidad moral mediante conceptos sofisticados sobre autodeterminación. Sus comentarios al 'De anima' influyeron enormemente en filósofos islámicos como Averroes y Avicena. En lógica, desarrolló la teoría del silogismo modal y refinó análisis aristotélicos sobre modalidad y predicación. Su interpretación naturalista de Aristóteles se opuso al neoplatonismo dominante, manteniendo vivo el aristotelismo secular que más tarde influiría en la filosofía medieval y renacentista.",
        
        "Plotino": "Plotino (c. 204-270 d.C.), fundador del neoplatonismo y último gran filósofo de la antigüedad clásica. Sus 'Enéadas', editadas por su discípulo Porfirio, presentan un sistema metafísico que dominó el pensamiento occidental durante mil años. Su filosofía de las tres hipóstasis - el Uno, el Intelecto (Nous) y el Alma (Psyche) - explica la realidad como emanación desde la unidad absoluta hacia la multiplicidad. El Uno trasciende ser y pensamiento, conocible solo mediante experiencia mística de 'unión' (henosis). El Intelecto contiene las Ideas platónicas como pensamientos divinos, mientras el Alma anima el cosmos material. Desarrolló una psicología compleja sobre la relación alma-cuerpo y teorías sobre la providencia divina que resuelven el problema del mal. Su experiencia mística directa del Uno (cuatro veces según Porfirio) establece la filosofía como camino espiritual. Influyó decisivamente en San Agustín, la teología cristiana, el misticismo islámico y judío, y el idealismo alemán, siendo redescubierto en el Renacimiento florentino.",
        
        "Proclo": "Proclo Licio (412-485 d.C.), último gran filósofo de la Academia platónica, quien sistematizó definitivamente el neoplatonismo tardío. Sus voluminosas obras preservan y desarrollan toda la tradición platónica, desde Platón hasta Plotino. Su 'Teología platónica' presenta la estructura jerárquica más compleja del mundo divino, con múltiples niveles de dioses, hénadas e inteligencias. Desarrolló la 'tríada proclusiana' (permanencia-procesión-retorno) como ley universal del cosmos, explicando cómo la realidad emana del Uno y regresa a él. Sus comentarios a diálogos platónicos establecieron metodologías exegéticas que influyeron en toda la hermenéutica posterior. En matemáticas, contribuyó a la geometría euclídea y desarrolló teorías sobre el infinito. Su obra 'Elementos de teología' presenta axiomáticamente todo el sistema neoplatónico mediante 211 proposiciones demostradas geométricamente. Practicó la teúrgia (magia ritual) como complemento filosófico para el ascenso del alma. Sus traducciones árabes influyeron en el mundo islámico, y su redescubrimiento renacentista impactó en Ficino, Pico della Mirandola y todo el hermetismo occidental.",
        
        "Porfirio": "Porfirio de Tiro (234-305 d.C.), discípulo de Plotino y principal responsable de la transmisión del neoplatonismo. Su edición de las 'Enéadas' organizó los escritos dispersos de su maestro en un sistema coherente que influyó en todo el pensamiento posterior. Su 'Isagoge' (Introducción) a las Categorías de Aristóteles planteó el famoso 'problema de los universales' que dominó la filosofía medieval: ¿existen los géneros y especies independientemente de los individuos? Sus distintos niveles de interpretación (literal, moral, físico, teológico) establecieron hermenéuticas que la exégesis cristiana adoptaría. Desarrolló una jerarquía de virtudes (cívicas, purificativas, contemplativas, paradigmáticas) como camino de ascensión espiritual. Su 'Vida de Pitágoras' y escritos sobre vegetarianismo influyeron en el ideal de vida filosófica. Como polemista anticristiano, su obra 'Contra los cristianos' (perdida) fue tan efectiva que emperadores cristianos ordenaron su destrucción. Sus comentarios a Platón, Aristóteles y textos herméticos preservaron tradiciones esotéricas que resurgirian en el Renacimiento.",
        
        "Jámblico": "Jámblico de Calcis (245-325 d.C.), neoplatónico sirio que transformó el platonismo en sistema teúrgico-religioso. Discípulo de Porfirio, se separó de él al enfatizar que la salvación del alma requiere ritos teúrgicos además de contemplación filosófica. Su 'De mysteriis' (Sobre los misterios) defiende las prácticas mágico-religiosas como medios legítimos de unión divina, estableciendo bases teóricas para toda la magia occidental posterior. Multiplicó las hipóstasis plotinianas en complejas jerarquías de dioses, arcángeles, ángeles, demonios y héroes, cada uno con funciones cósmicas específicas. Su interpretación del 'Parménides' platónico como teología sistemática influyó en toda la teología especulativa posterior. Reorganizó el currículo neoplatónico, estableciendo el orden canónico de lectura platónica que perduró mil años. Sus biografías pitagóricas idealizadas contribuyeron al mito renacentista de Pitágoras como mago-filósofo. La escuela siríaca que fundó mantuvo vivo el paganismo filosófico hasta Justiniano, y sus doctrines teúrgicas influiron en el hermetismo, la cábala cristiana y el ocultismo moderno.",
        
        "Simplicio": "Simplicio de Cilicia (490-560 d.C.), último gran comentarista de Aristóteles y Platón en la antigüedad, cuyas obras preservaron fragmentos invaluables de filósofos presocráticos perdidos. Miembro de la Academia cuando Justiniano la cerró (529 d.C.), se exilió temporalmente en Persia con otros filósofos paganos. Sus comentarios monumental al 'De caelo', 'Física' y 'Categorías' de Aristóteles son fuentes primarias para reconstruir el pensamiento presocrático, particularmente de Parménides, Empédocles y Anaxágoras. Desarrolló sofisticadas teorías sobre el infinito matemático y el continuo, anticipando problemas que solo resolverían matemáticos modernos. Su armonización de Platón y Aristóteles influyó en toda la filosofía bizantina e islámica. Defendió el paganismo intelectual mediante interpretaciones alegóricas de mitos griegos como verdades filosóficas profundas. Sus discusiones sobre lugar, vacío, tiempo y movimiento preservaron debates cruciales entre aristotélicos, neoplatónicos y estoicos. Las traducciones árabes de sus obras transmitieron el aristotelismo auténtico al mundo islámico, y su redescubrimiento renacentista contribuyó a la revolución científica moderna.",
        
        # Filósofos Medievales - Expansión masiva
        "Alberto Magno": "Alberto Magno (1200-1280), conocido como 'Doctor Universalis', fue el primer gran aristotélico del mundo cristiano y maestro de Tomás de Aquino. Este filósofo, teólogo, científico y obispo alemán introdujo sistemáticamente la obra completa de Aristóteles en Occidente, comentando prácticamente todo el corpus aristotélico. Sus investigaciones en ciencias naturales, especialmente alquimia, botánica, zoología y mineralogía, lo convirtieron en precursor del método experimental. Desarrolló una síntesis única entre aristotelismo, neoplatonismo y cristianismo que preparó el terreno para la Escolástica madura. Sus obras sobre los minerales, plantas y animales fueron las más avanzadas de su época, basadas en observación directa antes que en autoridades antiguas. Como profesor en París y Colonia, revolucionó la educación universitaria incorporando la lógica y metafísica aristotélicas al currículo teológico. Su concepto de la filosofía como 'ancilla theologiae' (sierva de la teología) dominó el pensamiento medieval durante siglos, estableciendo que la razón natural puede alcanzar verdades compatibles con la fe revelada.",
        
        "Boecio": "Anicio Manlio Torcuato Severino Boecio (480-525), último romano y primer escolástico, cuyas traducciones y comentarios preservaron la lógica aristotélica para Occidente durante siglos oscuros. Su 'Consolación de la filosofía', escrita en prisión antes de su ejecución, es una de las obras más influyentes de la literatura universal, consolando mediante argumentos filosóficos sobre la providencia, fortuna y felicidad verdadera. Sus traducciones de las 'Categorías' e 'Interpretación' de Aristóteles fueron los únicos textos lógicos disponibles hasta el siglo XII. Desarrolló el famoso problema de los universales en su comentario a Porfirio, planteando cuestiones que dominarían la filosofía medieval. Su definición de persona ('sustancia individual de naturaleza racional') influyó decisivamente en la teología trinitaria y cristológica. Como músico teórico, sus tratados sobre aritmética y música estructuraron el quadrivium medieval. Sus cinco opúsculos teológicos aplicaron por primera vez métodos filosóficos aristotélicos a doctrinas cristianas como Trinidad e Incarnación, estableciendo el modelo de la teología escolástica posterior.",
        
        "Buenaventura": "San Buenaventura de Bagnoregio (1221-1274), franciscano italiano conocido como 'Doctor Seráfico', quien desarrolló la síntesis más completa entre agustinismo tradicional y elementos aristotélicos seleccionados. Ministro General de la Orden Franciscana, defendió el ideal de pobreza evangélica contra las críticas seculares universitarias. Su 'Itinerarium mentis in Deum' (Itinerario del alma hacia Dios) presenta el ascenso místico por seis etapas de contemplación, desde creaturas materiales hasta unión trinitaria. Desarrolló la teoría de la iluminación divina como alternativa cristiana a la teoría aristotélica del conocimiento, sosteniendo que toda verdad requiere luz inteligible de Dios. Su 'Breviloquium' sintetiza toda la teología cristiana en estructura sistemática que influyó en la pedagogía franciscana durante siglos. Como filósofo de la historia, interpretó a San Francisco como 'ángel del sexto sello' apocalíptico, inaugurando la era final de perfección espiritual. Sus disputas con Tomás de Aquino sobre unidad/pluralidad de formas, eternidad del mundo y primacía de voluntad sobre intelecto definieron las controversias escolásticas centrales.",
        
        "Meister Eckhart": "Johannes Eckhart (1260-1328), dominico alemán conocido como Meister Eckhart, el más profundo místico especulativo del cristianismo occidental. Sus sermones alemanes revolucionaron el lenguaje filosófico vernáculo, creando conceptos como 'Abgeschiedenheit' (desasimiento), 'Durchbruch' (ruptura), y 'Gottheit' (divinidad). Su mística del 'fondo del alma' (Seelengrund) identifica la esencia del alma con la esencia divina, acercándose peligrosamente al panteísmo. Desarrolló una teología negativa radical donde Dios trasciende ser, bondad y verdad, siendo mejor llamado 'nada' que 'algo'. Su doctrina del 'nacimiento de Dios en el alma' presenta la unión mística como generación eterna del Verbo en el intelecto humano purificado. Influenciado por Proclo y Dionisio Areopagita, sintetizó neoplatonismo cristiano con innovaciones conceptuales que anticiparon el idealismo alemán. Procesado por herejía, defendió que sus expresiones paradójicas reflejan la inadecuación del lenguaje humano para verdades divinas. Su influencia en la mística renana, Tauler, Suso, y posteriormente en Cusano, Böhme, Hegel y Heidegger, lo convierte en figura crucial del pensamiento occidental.",
        
        "Duns Escoto": "Juan Duns Escoto (1266-1308), franciscano escocés llamado 'Doctor Sutil' por la precisión de sus análisis conceptuales. Desarrolló el voluntarismo teológico más sofisticado, argumentando que la voluntad divina es absolutamente libre y no determinada por consideraciones racionales externas. Su prueba de la existencia de Dios mediante la noción de 'ser infinito' refinó el argumento ontológico anselmiano con distinciones modales rigurosas. La doctrina del 'haecceitas' (esteidad) explica la individuación mediante principios formales específicos, no solo por materia como en Tomás de Aquino. Su teoría del conocimiento intuitivo directo de singulares influyó decisivamente en Ockham y el nominalismo posterior. Defendió la Inmaculada Concepción mediante argumentos de 'potuit, decuit, ergo fecit' (pudo, convino, por tanto lo hizo) que la Iglesia adoptaría oficialmente. Sus distinciones formales entre atributos divinos y análisis modales sobre necesidad/contingencia anticiparon desarrollos lógicos modernos. Como teólogo mariano, elevó el culto a la Virgen mediante especulaciones sobre su papel en la economía salvífica, influyendo en toda la devoción franciscana posterior.",
        
        "Guillermo de Ockham": "Guillermo de Ockham (1287-1347), franciscano inglés cuyo nominalismo revolucionó la filosofía medieval tardía y preparó la modernidad. Su famosa 'navaja' ('no hay que multiplicar entes sin necesidad') estableció principios de economía conceptual que la ciencia moderna adoptaría. Negó la existencia real de universales, sosteniendo que solo existen individuos singulares y que los términos generales son meros signos mentales sin referentes extramentales. Su teoría del conocimiento intuitivo directo de singulares eliminó especies inteligibles intermediarias, estableciendo contacto inmediato sujeto-objeto que anticipa el empirismo moderno. Desarrolló una lógica terminista sofisticada que analizó proposiciones según propiedades semánticas de términos (suposición, amplificación, restricción). Su voluntarismo teológico radical sostuvo que la moral depende completamente de mandatos divinos arbitrarios, no de esencias racionales eternas. Como teórico político, defendió la separación de poderes espiritual y temporal contra pretensiones papales teocráticas. Sus disputas con el Papa Juan XXII sobre pobreza franciscana lo llevaron al exilio en Munich, donde desarrolló teorías conciliaristas que limitaban la autoridad pontificia.",
        
        # Filósofos Orientales - Expansión masiva
        "Mencio": "Mencio (372-289 a.C.), conocido en chino como Mengzi, segundo gran filósofo confuciano que desarrolló la teoría de la bondad innata de la naturaleza humana. Su doctrina de que 'el hombre es naturalmente bueno' se opuso al pesimismo de Xunzi, estableciendo un optimismo antropológico que dominó el confucianismo posterior durante dos milenios. Desarrolló la teoría de los 'cuatro brotes' (si duan): compasión (origen de humanidad ren), vergüenza (origen de justicia yi), cortesía (origen de ritos li), y discernimiento moral (origen de sabiduría zhi). Su filosofía política defendió el derecho de rebelión contra gobernantes injustos mediante la doctrina del 'mandato del cielo' (tianming) que se retira de dinastías corruptas. Sus debates con filósofos mohistas y legalistas sobre naturaleza humana, moralidad y gobierno establecieron problemas centrales de la filosofía china. Desarrolló técnicas dialécticas sofisticadas usando analogías, parábolas y casos ejemplares para demostrar puntos morales. Su influencia en el neoconfucianismo Song-Ming fue enorme, siendo redescubierto como alternativa humanística al budismo y taoísmo durante renovaciones confucianas. Sus ideas sobre educación moral, cultivo personal y gobierno benevolente siguieron influyendo en Asia Oriental hasta la modernidad.",
        
        "Mozi": "Mozi (470-391 a.C.), fundador del mohismo, primera escuela filosófica china organizada sistemáticamente que se opuso al confucianismo dominante. Su ética del 'amor universal' (jian ai) propuso extender el afecto más allá de la familia hacia toda la humanidad, contrastando con la moralidad particularista confuciana basada en relaciones jerárquicas. Desarrolló el principio de 'beneficio mutuo' (xiang li) como criterio para evaluar instituciones sociales, anticipando aspectos del utilitarismo occidental. Su filosofía política defendió la meritocracia absoluta donde posiciones se asignan por talento y virtud, no por nacimiento o conexiones familiares. Como filósofo de la religión, argumentó por la existencia de espíritus y fantasmas que recompensan virtud y castigan vicio, oponiéndose al escepticismo confuciano sobre lo sobrenatural. Sus teorías sobre 'economía en gastos' criticaron rituales confucianos elaborados como derroche de recursos sociales que podrían beneficiar a los pobres. Desarrolló primitivas teorías contractuales sobre el origen del gobierno y criterios epistemológicos para evaluar conocimiento (basándose en origen, verificabilidad y aplicabilidad). Su escuela mantuvo sofisticadas tradiciones de lógica, óptica, mecánica y fortificación militar que influyeron en el desarrollo tecnológico chino.",
        
        "Zhuangzi": "Zhuangzi (369-286 a.C.), conocido como Maestro Zhuang, segundo fundador del taoísmo tras Laozi, cuya obra combina profundidad filosófica con genio literario incomparable. Sus parábolas, alegorías y paradojas desarrollaron una filosofía de la relatividad radical que cuestiona todas las distinciones convencionales como vida/muerte, grande/pequeño, útil/inútil, verdadero/falso. Su concepto de 'wu wei' (no-acción) no significa pasividad sino actuar en armonía natural sin forzar situaciones mediante cálculos artificiales. La famosa parábola del sueño de la mariposa explora problemas epistemológicos sobre realidad/ilusión que anticipan el solipsismo y filosofías de la consciencia occidentales. Su ideal del 'hombre perfecto' (zhenren) trasciende limitaciones sociales, morales y cognitivas ordinarias alcanzando libertad espiritual absoluta. Sus críticas al confucianismo atacan la moralidad convencional como fuente de conflicto y sufrimiento, proponiendo retorno a simplicidad natural primordial. Desarrolló teorías sofisticadas sobre transformación constante (hua) como ley cósmica fundamental donde muerte es mera metamorfosis, no extinción. Su influencia en arte, literatura y filosofía china fue inmensa, ofreciendo alternativa libertaria al autoritarismo legalista y al moralismo confuciano durante toda la historia china.",
        
        "Nagarjuna": "Nagarjuna (150-250 d.C.), fundador de la escuela Madhyamaka ('Camino Medio') del budismo Mahayana, cuya filosofía de la vacuidad (śūnyatā) revolucionó el pensamiento budista. Su 'Mūlamadhyamakakārikā' (Versos fundamentales sobre el Camino Medio) desarrolló la doctrina de que todos los fenómenos están 'vacíos' de existencia inherente, existiendo solo mediante originación dependiente (pratītyasamutpāda). Su método dialéctico de 'tetralemma' (catuṣkoṭi) refuta sistemáticamente todas las posiciones posibles sobre cualquier tema: afirmación, negación, ambas, ninguna. Esta lógica paradójica deconstruye conceptos sustancialistas mostrando que análisis último disuelve todas las categorías del pensamiento ordinario. Su crítica del 'svabhāva' (naturaleza propia) argumenta que la creencia en esencias fijas es la raíz del sufrimiento, pues genera apego y aversión. Desarrolló la doctrina de las 'dos verdades': convencional (saṃvṛti) para la vida práctica y última (paramārtha) que revela la vacuidad universal. Su influencia se extendió por todo Asia, inspirando desarrollos en budismo tibetano, chino, japonés y coreano. Sus sofisticadas técnicas de análisis conceptual anticiparon aspectos de la filosofía analítica occidental y la deconstrucción contemporánea, estableciendo el budismo como sistema filosófico riguroso comparable a tradiciones occidentales e indias.",
        
        "Shankara": "Adi Shankara (788-820), reformador religioso y filósofo que estableció el Advaita Vedanta como interpretación ortodoxa del hinduismo, unificando tradiciones védicas dispersas en sistema coherente. Su comentario al 'Brahma Sutra' de Badarayana sistematizó la doctrina de que Brahman (Absoluto impersonal) y Atman (Ser individual) son idénticos, y que la multiplicidad fenoménica es maya (ilusión cósmica). Desarrolló sofisticadas técnicas hermenéuticas para armonizar textos upanisádicos aparentemente contradictorios, estableciendo principios interpretativos que dominaron la exégesis hindú posterior. Su teoría de los tres niveles de realidad (paramārtha/absoluto, vyāvahārika/empírico, prātibhāsika/ilusorio) resolvió problemas sobre relación entre Absoluto inmutable y mundo cambiante. Como organizador religioso, estableció cuatro monasterios (maṭhas) en esquinas cardinales de India que mantuvieron tradiciones védicas durante invasiones islámicas. Sus himnos devocionales aparentemente contradicen su filosofía no-dualista, pero ilustran niveles pedagógicos adapatados a capacidades espirituales diversas. Su síntesis de jñāna (conocimiento), bhakti (devoción) y karma (acción) influyó en todo el hinduismo posterior, desde Ramanuja hasta movimientos modernos como Ramakrishna y Vivekananda.",
        
        # Filósofos Modernos - Expansión masiva  
        "John Dewey": "John Dewey (1859-1952), filósofo estadounidense que desarrolló el pragmatismo clásico en direcciones pedagógicas, políticas y estéticas revolucionarias. Su filosofía educativa 'aprender haciendo' transformó sistemas escolares mundialmente, enfatizando experiencia directa sobre memorización de contenidos abstractos. Su teoría de la experiencia como transacción continua organismo-ambiente superó dualismos tradicionales mente/cuerpo, sujeto/objeto, teoría/práctica mediante conceptos procesales dinámicos. Desarrolló una ética naturalista donde valores emergen de experiencias problemáticas que requieren reconstrucción inteligente, no de principios a priori eternos. Su filosofía política 'democracia participativa' propuso que instituciones democráticas deben extenderse más allá del gobierno hacia educación, economía y cultura para desarrollar plenamente capacidades humanas. Sus contribuciones a lógica pragmatista reconceptualizaron el pensamiento como instrumento para resolver problemas vitales, no para contemplar verdades eternas. Como reformador social, aplicó principios filosóficos a cuestiones concretas como sufragio femenino, derechos laborales, educación progresiva y pluralismo cultural. Su influencia internacional se extendió desde China (donde enseñó) hasta América Latina, estableciendo el pragmatismo como alternativa democrática tanto al idealismo autoritario como al materialismo dogmático.",
        
        "William James": "William James (1842-1910), psicólogo y filósofo estadounidense que fundó tanto la psicología moderna como el pragmatismo filosófico. Su 'Principios de Psicología' estableció la psicología como ciencia empírica independiente de la filosofía especulativa, desarrollando conceptos como 'corriente de consciencia' que influyeron en literatura y arte modernos. Su pragmatismo define verdad como 'lo que funciona en la práctica', revolutionando epistemología tradicional al evaluar ideas por consecuencias vitales en lugar de correspondencia con realidad absoluta. Su 'empirismo radical' propuso que relaciones son tan reales como términos relacionados, superando atomismo asociacionista mediante visión holística de experiencia. Sus estudios pioneros sobre experiencia religiosa aplicaron métodos empíricos a fenómenos místicos, defendiendo legitimidad cognitiva de estados alterados de consciencia contra reduccionismos materialistas. Desarrolló el concepto de 'voluntad de creer' para justificar fe religiosa en ausencia de evidencia concluyente cuando stakes existenciales están involucrados. Su pluralismo filosófico rechazó sistemas monistas totalitarios, defendiendo que realidad es múltiple, abierta y en proceso constante de creación. Como escritor brillante, popularizó filosofía académica sin sacrificar rigor, influyendo en generaciones de intelectuales públicos que ven filosofía como herramienta para vivir mejor.",
        
        "Max Weber": "Max Weber (1864-1920), sociólogo, economista y filósofo alemán que desarrolló metodologías científico-sociales fundamentales y análisis penetrantes de la modernidad occidental. Su 'Ética protestante y espíritu del capitalismo' argumenta que valores religiosos puritanos promovieron inadvertidamente actitudes racionales hacia trabajo y acumulación que facilitaron el desarrollo capitalista. Desarrolló la metodología de 'tipos ideales' como herramientas heurísticas para analizar fenómenos sociales complejos sin pretender describir realidad empírica exactamente. Su teoría de la acción social distingue cuatro tipos: tradicional, afectiva, racional con arreglo a valores, y racional con arreglo a fines, proporcionando marco conceptual básico para sociología comprensiva. Sus estudios comparativos sobre religiones mundiales (judaísmo, cristianismo, islam, hinduismo, budismo, confucianismo) analizaron cómo diferentes sistemas de creencias facilitaron o inhibieron desarrollos económicos y políticos específicos. Su concepto de 'desencantamiento del mundo' (Entzauberung der Welt) describió el proceso histórico donde explicaciones mágico-religiosas son reemplazadas por racionalización científico-técnica, con consecuencias ambivalentes para significado existencial. Desarrolló tipologías de dominación política (tradicional, carismática, legal-racional) que iluminan dinámicas del poder en sociedades modernas.",
        
        "Hans-Georg Gadamer": "Hans-Georg Gadamer (1900-2002), filósofo alemán que revolucionó la hermenéutica transformándola de metodología específica para ciencias humanas en filosofía universal sobre comprensión humana. Su monumental 'Verdad y método' argumenta que comprensión es siempre 'fusión de horizontes' entre intérprete y texto, mediada por tradición histórica que condiciona pero también posibilita entendimiento. Desarrolló conceptos como 'historia efectual' (Wirkungsgeschichte) para mostrar cómo tradiciones pasadas influyen inconscientemente en comprensión presente, requiriendo 'conciencia hermenéutica' que reconozca estos condicionamientos sin pretender superarlos completamente. Su crítica del 'método' científico moderno argumenta que verdades más importantes (arte, filosofía, literatura) no son accesibles mediante procedimientos objetivantes que tratan objetos como manipulables técnicamente. La hermenéutica gadameriana enfatiza 'aplicación' (Anwendung) como momento esencial de comprensión: entender textos significa aplicarlos a situaciones presentes, no reconstruir significados originales abstractos. Sus análisis sobre 'juego' (Spiel) como modelo de experiencia estética muestran cómo arte involucra participación activa que transforma tanto obra como espectador. Su influencia se extendió más allá de filosofía hacia crítica literaria, teología, jurisprudencia y ciencias sociales, estableciendo hermenéutica como alternativa continental al positivismo analítico anglosajón.",
        
        "Paul Ricoeur": "Paul Ricoeur (1913-2005), filósofo francés que desarrolló hermenéutica sofisticada integrando fenomenología, estructuralismo, psicoanálisis y filosofía analítica en síntesis creativa. Su filosofía del símbolo exploró cómo significados múltiples se condensan en expresiones culturales (mitos, metáforas, símbolos religiosos) que requieren interpretación para revelar verdades sobre condición humana. Desarrolló la 'hermenéutica de la sospecha' aplicando métodos críticos de Marx, Nietzsche y Freud para desenmascar ar significados ocultos, seguida por 'hermenéutica de la restauración' que recupera sentidos auténticos. Sus estudios sobre narratividad argumentan que identidad personal se constituye mediante relatos que articulan experiencia temporal dispersa en totalidades significativas, influyendo enormemente en teoría literaria y psicología narrativa contemporánea. Su ética desarrolló distinciones entre 'moral' (normas universales) y 'ética' (vida buena en instituciones justas) que renuevan tradiciones aristotélicas para contextos pluralistas modernos. Como fenomenólogo, sus análisis sobre voluntad, memoria, perdón y reconocimiento expandieron investigaciones husserlianas hacia dimensiones intersubjetivas y políticas. Su método de 'injerto' hermenéutico sobre fenomenología mostró cómo descripción pura requiere mediación interpretativa mediante lenguaje, cultura e historia. Sus contribuciones a filosofía jurídica, teología y ciencias sociales establecieron hermenéutica como disciplina interdisciplinaria fundamental.",
        
        "Walter Benjamin": "Walter Benjamin (1892-1940), crítico cultural, filósofo y ensayista alemán que desarrolló una teoría crítica única combinando marxismo, misticismo judío, y estética vanguardista. Su ensayo 'La obra de arte en la época de su reproducibilidad técnica' analizó cómo tecnologías modernas (fotografía, cine) transforman la experiencia estética eliminando el 'aura' de obras originales y democratizando el acceso cultural. Desarrolló conceptos como 'imagen dialéctica' y 'constelación' para describir momentos históricos donde pasado y presente se iluminan mutuamente, revelando potencialidades revolucionarias latentes. Su filosofía de la historia, resumida en las 'Tesis sobre el concepto de historia', critica concepciones progresistas lineales proponiendo una metodología mesiánica que 'cepilla la historia a contrapelo' para rescatar memorias de los oprimidos. Sus estudios sobre Baudelaire y París del siglo XIX (en el inconcluso 'Libro de los Pasajes') aplicaron técnicas montage cinematográfico al análisis histórico-cultural, influyendo en metodologías interdisciplinarias posteriores. Como traductor teórico, sus ensayos sobre traducción influyeron en hermenéutica y estudios literarios comparativos, argumentando que traducción revela 'afinidad suprahistórica' entre lenguas. Su suicidio en la frontera franco-española mientras huía del nazismo lo convirtió en mártir intelectual, y su influencia póstuma se extendió desde la Escuela de Frankfurt hasta estudios culturales contemporáneos.",
        
        "Antonio Gramsci": "Antonio Gramsci (1891-1937), teórico político y filósofo marxista italiano que desarrolló conceptos de hegemonía cultural y revolución pasiva que renovaron profundamente la teoría marxista. Sus 'Cuadernos de la cárcel', escritos durante encarcelamiento fascista, analizan por qué revoluciones socialistas no ocurrieron en Occidente desarrollado como predijo Marx. Su concepto de 'hegemonía' explica cómo clases dominantes mantienen poder no solo mediante coerción estatal sino fundamentalmente a través de consenso cultural que naturaliza su dominación en educación, religión, medios y sentido común. Desarrolló la distinción entre 'sociedad civil' (instituciones culturales) y 'sociedad política' (aparato estatal) mostrando cómo lucha de clases se libra en ambos terrenos simultáneamente. Su teoría del 'intelectual orgánico' propuso que cada clase social genera pensadores que articulan y difunden su visión del mundo, contrastando con 'intelectuales tradicionales' que se perciben como neutrales. Sus análisis sobre 'transformismo' y 'revolución pasiva' examinaron cómo sistemas dominantes incorporan desafíos mediante reformas que neutralizan potencial revolucionario. Sus contribuciones a filosofía de la praxis integraron Marx con Croce y Labriola, enfatizando dimensiones culturales y subjective de cambio social. Su influencia se extendió desde partidos comunistas europeos hasta estudios culturales, postcolonialismo y teoría crítica contemporánea.",
        
        # CONTINUACIÓN - Más filósofos con biografías extensas
        "Arthur Schopenhauer": "Arthur Schopenhauer (1788-1860), filósofo alemán que desarrolló un sistema pesimista influenciado por Kant y filosofía oriental. Su obra maestra 'El mundo como voluntad y representación' propone que la realidad fenoménica es 'representación' (Vorstellung) regida por principios de razón suficiente, mientras la cosa-en-sí kantiana es 'voluntad' (Wille), fuerza ciega e irracional que impulsa toda existencia. Su pesimismo filosófico argumenta que la vida es esencialmente sufrimiento: la voluntad genera deseo constante, y satisfacer deseos solo produce aburrimiento temporal antes de nuevos sufrimientos. Desarrolló una estética revolucionaria donde contemplación artística libera temporalmente de la tiranía de la voluntad mediante conocimiento intuitivo de Ideas platónicas. Su ética de la compasión sostiene que reconocer la identidad metafísica con otros seres sufrientes es el único fundamento auténtico de moralidad. Fue pionero occidental en estudiar seriamente filosofías indias, especialmente Upanishads y budismo, influyendo en el orientalismo filosófico europeo. Su prosa brillante y críticas mordaces contra académicos contemporáneos lo convirtieron en escritor filosófico popular. Su influencia en Nietzsche, Wagner, Freud y el existencialismo fue enorme, estableciendo temas fundamentales sobre irracionalidad, pesimismo y crítica de la modernidad optimista.",
        
        "Edmund Husserl": "Edmund Husserl (1859-1938), matemático y filósofo alemán que fundó la fenomenología, uno de los movimientos filosóficos más influyentes del siglo XX. Su método fenomenológico propone 'volver a las cosas mismas' mediante descripción pura de estructuras de consciencia sin presupuestos teóricos o metafísicos. Desarrolló la 'reducción fenomenológica' o 'epoché', suspensión de la 'actitud natural' que asume ingenuamente la existencia del mundo, para estudiar cómo objetos se constituyen en consciencia. Su concepto de 'intencionalidad' - toda consciencia es consciencia de algo - revolucionó la filosofía de la mente mostrando que consciencia y objeto son correlativos e inseparables. Sus 'Investigaciones lógicas' criticaron el psicologismo en lógica y matemática, estableciendo objetividad de significados ideales independientes de actos psicológicos particulares. Desarrolló complejas teorías sobre temporalidad de consciencia, mostrando cómo presente viviente se constituye mediante retención de pasado inmediato y protención hacia futuro inminente. Su noción de 'mundo de vida' (Lebenswelt) como horizonte pre-teórico de experiencia influyó enormemente en existencialismo, hermenéutica y filosofía continental. Su escuela fenomenológica produjo pensadores como Heidegger, Sartre, Merleau-Ponty y Levinas, transformando filosofía europea del siglo XX.",
        
        "Emmanuel Levinas": "Emmanuel Levinas (1906-1995), filósofo lituano-francés que desarrolló una ética radical basada en el 'rostro del Otro' como fundamento primordial de toda filosofía. Su experiencia como prisionero de guerra judío durante el Holocausto marcó profundamente su pensamiento sobre alteridad, responsabilidad y ética. Su obra 'Totalidad e infinito' critica la tradición filosófica occidental como 'ontología' que reduce el Otro al Mismo mediante conceptualización totalizante, oponiéndole una 'metafísica' que preserva la alteridad radical del Otro. El 'rostro' (visage) no es fenómeno observable sino encuentro ético primordial que precede toda ontología: el rostro 'habla' ordenando 'no matarás' y constituyendo subjetividad como responsabilidad infinita. Desarrolló conceptos como 'il y a' (hay ser) para describir existencia anónima e impersonal que precede personalización, y 'decir' vs. 'dicho' para distinguir evento ético originario de su tematización conceptual posterior. Sus análisis sobre tiempo, alteridad y trascendencia ofrecieron alternativas al ser heideggeriano mediante 'lo absolutamente Otro' que interrumpe totalidades ontológicas. Su influencia en filosofía contemporánea, teología, estudios religiosos y ética aplicada es inmensa, renovando tradiciones éticas mediante radicalización de responsabilidad intersubjetiva que precede libertad y conocimiento."
    }
    
    # Si existe biografía detallada, devolverla
    if name in DETAILED_BIOGRAPHIES:
        return DETAILED_BIOGRAPHIES[name]
    
    # Biografías más específicas por categoría para otros filósofos
    generic_biographies = {
        # Presocráticos
        "Tales de Mileto": f"{name}, considerado el primer filósofo occidental, propuso que el agua es el principio fundamental de todas las cosas. Fue también matemático y astrónomo, miembro de los Siete Sabios de Grecia.",
        "Anaximandro": f"{name}, discípulo de Tales, propuso el 'ápeiron' (lo indefinido) como principio universal. Creó el primer mapa del mundo conocido y desarrolló teorías evolutivas primitivas.",
        "Anaxímenes": f"{name}, último filósofo de Mileto, consideró el aire como elemento primordial. Sus teorías sobre condensación y rarefacción influyeron en cosmogonías posteriores.",
        
        # Neoplatónicos
        "Plotino": f"{name}, fundador del neoplatonismo, desarrolló la filosofía de las tres hipóstasis: el Uno, el Intelecto y el Alma. Sus 'Enéadas' influyeron profundamente en el cristianismo.",
        "Proclo": f"{name} fue el último gran filósofo neoplatónico que dirigió la Academia platónica. Desarrolló una compleja teología filosófica que influyó en el pensamiento medieval.",
        
        # Filósofos Medievales menores
        "Anselmo de Canterbury": f"{name}, arzobispo y filósofo del siglo XI, famoso por su argumento ontológico para demostrar la existencia de Dios y el principio 'fides quaerens intellectum'.",
        "Pedro Abelardo": f"{name}, filósofo escolástico del siglo XII, desarrolló la dialéctica teológica. Su historia amorosa con Eloísa y su conceptualismo lo convirtieron en figura emblemática.",
        
        # Filósofos Orientales
        "Nagarjuna": f"{name}, filósofo budista del siglo II, fundó la escuela Madhyamaka. Desarrolló la doctrina de la vacuidad (sunyata) y el camino medio budista.",
        "Mencio": f"{name}, filósofo confuciano chino, desarrolló la teoría de la bondad intrínseca de la naturaleza humana y defendió el gobierno benevolente.",
        "Zhuangzi": f"{name}, filósofo taoísta chino, escribió textos llenos de paradojas sobre la relatividad, transformación constante y libertad espiritual."
    }
    
    if name in generic_biographies:
        return generic_biographies[name]
    
    # Fallback genérico pero más informativo
    return f"{name} fue un filósofo influyente cuyo pensamiento contribuyó significativamente al desarrollo de la tradición filosófica occidental y oriental."